### ISSUE TITLE
Failed to use "poison" (versions 1.5.0 to 2.2.0) because

### ISSUE THREAD

**Issue by SethArchambault** [Bandwidth/elixir-bandwidth#2]
When I run

`sudo mix deps.get --only prod
`
I get this:

```
Failed to use "poison" (versions 1.5.0 to 2.2.0) because
  bandwidth (version 1.2.1) requires ~> 1.4.0
  phoenix (version 1.2.1) requires ~> 1.5 or ~> 2.0
```

**Comment by dtolb** [comment]
@SethArchambault Awesome that you're using our Elixir SDK for bandwidth. This was done as a pet project by a former employee and is *unfortunately* not supported at this time.

If @wtcross or @a-type is able to dedicate some time, they _may be_ able to help. 

Of course, I encourage you to take a look and open a Pull Request yourself :) .

Let me know if you have any questions.

**Comment by rlonstein** [comment]
https://github.com/Bandwidth/elixir-bandwidth/pull/3

Was merged and probably resolves this.
